config/routes.rb
  Altijdheerlijk::Application.routes.draw do
  resources :pins do
    member do
      put "like", to: "pins#like"
      put "unlike", to: "pins#unlike"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  match '/users/:id/follow' => 'follows#create', :as => :user_follow, :via => [:post]
  match '/users/:id/unfollow' => 'follows#destroy', :as => :user_unfollow, :via => [:delete]

  resources :users 

  root "users#feeds"
  get "my_friends_pins" => "users#feeds"
  get "my_pins" => "pins#my_pins"
  get "my_favorites" => "pins#my_favorites"
  get "my_friends" => "users#my_friends"
  get "followers" => "users#followers"
  
  get '/feeds' => 'users#feeds', :as => :feeds
  
  

  

end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :followable, :polymorphic => true
	belongs_to :user

	scope :get_follow, lambda {|follow| where(:followable_id => follow.id, :followable_type => follow.class.to_s)}
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :pins
  has_many :users
  has_many :follows, :dependent => :destroy
  has_many :followers, :class_name => 'Follow', :dependent => :destroy, :as => :followable
  has_many :followings, :through => :follows, :source => :followable, :source_type => 'User'

  acts_as_voter
  acts_as_votable

	def self.from_omniauth(auth)
      where(provider2: auth.provider, uid2: auth.uid).first_or_create do |user|
        user.provider2 = auth.provider
        user.uid2 = auth.uid
        user.email = auth.info.email
        user.name = auth.info.name
        user.image_file_name = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
  end

  def follow!(user, source=nil)
    follow = self.follows.new
    follow.followable = user
    follow.save!
  end

  def following?(follow)
    follow = self.follows.get_follow(follow)
    follow.size > 0 ? true : false
  end 

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/default.jpg"

  private
    def send_welcome_email
      ModelMailer.new_user_account_notification(self).deliver
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
before_action :authenticate_user!

protect_from_forgery with: :exception
before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :image_file_name, :email, :password, :password_confirmation, :current_password) }
   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :image_file_name, :email, :password, :password_confirmation, :current_password) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :image_file_name, :email, :password, :password_confirmation, :current_password) }
end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
      	sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      	set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    	else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  before_action :authenticate_user!

  def create
    @user = User.find(params[:id])
    if @user.present?
      current_user.follow!(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.present?
      follow = current_user.follows.get_follow(@user).first if current_user.follows
      if follow
        follow.destroy
      end
    end
    respond_to do |format|
      format.js { render :file => "/follows/create", :handlers => [:erb] }
    end
  end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:destroy]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def my_pins
    @pins = current_user.pins
  end

  def my_favorites
    @pins = current_user.find_liked_items
  end

  def like
    @pin.liked_by current_user
    redirect_to :back, notice: 'Je hebt dit recept nu toegevoegd aan jouw bewaarde recepten.'
    current_user_follower_ids = current_user.followers.pluck(:user_id)
    User.find(current_user_follower_ids).each do |follower|
    ModelMailer.new_like_notification(@pin, follower, current_user).deliver
  end
  end

  def unlike
    @pin.unliked_by current_user
    redirect_to :back, notice: 'Dit recept is verwijderd uit jouw bewaarde recepten.'
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save    
      redirect_to @pin, notice: 'Jouw recept is toegevoegd aan Altijd heerlijk.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Recept is gewijzigd.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Het is alleen toegestaan om eigen recepten te wijzigen" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :preparation, :ingredients2)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :authenticate_user!, except: [:index, :show]

	def show
		@user = User.find(params[:id])
		respond_to do |format|
		  format.html # show.html.erb
		  format.xml  { render :xml => @user }
		end
	end

	def index
	  @user = User.all.order("updated_at DESC")
	end

	def my_friends
		@followings = current_user.followings
	end

	def followers
		@followers = current_user.followers.collect(&:user)
	end

	def feeds
    current_users_follower_pin_ids = []
    current_user.follows.each do |follower|
    current_users_follower_pin_ids << follower.followable.votes.pluck(:votable_id)
    end
    @pins = Pin.find(current_users_follower_pin_ids.flatten.uniq)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/follows/create.html.erb
<h1>Follows#create</h1>
<p>Find me in app/views/follows/create.html.erb</p>

app/views/follows/create.js.erb
<% if @user %>
  $('#user_<%= @user.id %>').html('<%= escape_javascript(render :partial => 'users/user', :locals => { :user => @user }) %>');
<% end %>

app/views/follows/destroy.html.erb
<h1>Follows#destroy</h1>
<p>Find me in app/views/follows/destroy.html.erb</p>

app/views/follows/destroy.js.erb
 $("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
              <li><%= link_to "Mijn favoriete recepten", my_favorites_path %></li> 
              <li><%= link_to "Zoek recepten", pins_path %></li> 
              <li><%= link_to "Mijn vrienden", my_friends_path %></li>
              <li><%= link_to "Zoek vrienden", users_path %></li> 
              <li><%= link_to "Log uit", destroy_user_session_path, method: :delete %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Altijdheerlijk</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59755392-1', 'auto');
  ga('send', 'pageview');

</script>
  
</head>
<body>


<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= render 'layouts/header' %>
<div class="container">


	
<%= yield %>


</body>

</html>

app/views/pages/home.html.erb
<h1>Welkom bij Altijd Heerlijk</h1>
<div class="jumbotron center">
	<% if user_signed_in? %>	
		Bekijk <%= link_to "mijn recepten", pins_path, class: "btn btn-info" %> of maak een 
		<%= link_to "nieuw recept", new_pin_path, class: "btn btn-info" %> aan.
     <% else %>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-info" %> of  
		<%= link_to "Meld je aan", new_user_registration_path, class: "btn btn-info" %> om zelf recepten toe te voegen.
	<% end %>  

    </p>    
</div>

app/views/pins/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">

    <%= form_for @pin, html: {multipart: true} do |f| %>
      <% if @pin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

          <ul>
          <% @pin.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      

      <div class="form-group">
        <%= f.label :description, "Naam gerecht (verplicht)" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :ingredients2, "Ingrediënten" %>
        <%= f.text_field :ingredients2, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :preparation, "Bereidingswijze" %>
        <%= f.text_field :preparation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image, "Foto van recept" %>
        <%= f.file_field :image, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Opslaan ", class: "btn btn-success" %>
      </div>
    <% end %>

</div>
</div>

app/views/pins/_show_pin_details.html.erb
  <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
          <div class="box panel panel-default">
                  <div class="panel-body">
                            <p><b>Recept:</b> <%= link_to pin.description, pin_path(pin) %></p>
                            <br><%= link_to image_tag(pin.image.url), pin %></br>
                              <br></br>
                                <div class="actions">
                                      <p><%= link_to pin_path(pin) , class: "btn btn-info btn-sm" do %>
                                      <span class="glyphicon glyphicon-fullscreen"></span>
                                      Bekijk recept
                                      <% end %>
                                      <% if current_user.liked? pin %>
                                        <%= link_to unlike_pin_path(pin), method: :put, class: "btn btn-danger btn-sm" do %>
                                        <span class="glyphicon glyphicon-remove"></span>
                                        Unlike
                                        <% end %>
                                      <% else %>
                                        <%= link_to like_pin_path(pin), method: :put, class: "btn btn-success btn-sm" do %>
                                        <span class="glyphicon glyphicon-heart"></span>
                                        Like 
                                        <% end %>
                                      <% end %></p>
                                      <p><b>Favoriet recept van: </b></p>
                                          <% pin.votes_for.voters.each do |p| %> 
                                          <% if p.present? %>
                                           <p><%= link_to p.name, user_path(@user) %></p>
                                           <% end %>   
                                      <% end %>  

                                </div>
                  </div>
          </div>
    <% end %>
  </div>

app/views/pins/edit.html.erb
<h1>Wijzig recept</h1>

<%= render 'form' %>

<%= link_to 'Toon recept', @pin %> |
<%= link_to 'Terug', pins_path %>

app/views/pins/index.html.erb
<h1>Zoek recepten</h1>
<p>Bekijk hier alle <b><%= @pins.count %> recepten</b> die op Altijd Heerlijk te vinden zijn. 
<u>Tip:bewaar jouw favoriete recepten.</u></p> 
<%= render 'pins/show_pin_details' %>  

app/views/pins/mijn_bewaarde_recepten.html.erb
<h1>Mijn profiel</h1>

<div class="row">
  <div class="col-md-offset-0 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <strong>
        <p>Jouw opgeslagen recepten
        </strong><br></br>
        Aantal recepten: 
        <strong>
        <%= @pins.count %>
        </strong></p>
        </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>  
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
          <div class="panel-body">
          <strong><p><%= pin.description %></p></strong>
          <p><%= link_to 'Bekijk recept', pin_path(pin) %></p>
            <% if pin.user == current_user %>
              <div class="actions">
                <p><span class="glyphicon glyphicon-heart"></span>
                Mmmmmm! </p> 
                  <div class="btn-group.pull-right">
                  <%= link_to 'Wijzig', edit_pin_path(pin), class:"btn btn-default" %>
                  <%= link_to 'Verwijder', pin_path(pin), method: :delete, data: { confirm: 'Weet je het zeker?' }, class:"btn btn-default" %>
                  </div>
              </div>
            <% end %>
          </div>
    </div>
  <% end %>


<% else %>
<%= render 'pages/login' %>
<% end %>

app/views/pins/my_favorites.html.erb
<h1>Mijn favoriete recepten</h1>
<p>Bekijk hier jouw <b><%= current_user.find_liked_items.size %></b> favoriete recepten.</p> 
<%= render 'pins/show_pin_details' %>  


app/views/pins/new.html.erb
<h1>Nieuw recept</h1>

<%= render 'form' %>

<%= link_to 'Terug', pins_path %>

app/views/pins/show.html.erb
<%= link_to :back, class: "btn btn-default" do %>
<span class="glyphicon glyphicon-chevron-left"></span>
Back
<% end %>
<% if current_user.liked? @pin %>
  <%= link_to unlike_pin_path(@pin), method: :put, class: "btn btn-danger btn-sm" do %>
  <span class="glyphicon glyphicon-remove"></span>
  Unlike
  <% end %>
<% else %>
  <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-success btn-sm" do %>
  <span class="glyphicon glyphicon-heart"></span>
  Like
  <% end %>
<% end %>

<h1><%= @pin.description %></h1>

  <div class="col-md-offset-0 col-md-14">
    <div class="panel panel-default">
      <div class="panel-body">
            <p><b>Favoriet recept van: </b></p>
                <% @pin.votes_for.voters.each do |p| %> 
                  <p><%= link_to image_tag(p.image_file_name), @user %></p>
                <% end %>  
      </div>
    </div>
  </div>

      <div class="panel panel-default">
      <div class="panel-body">
          <p><strong>Ingrediënten:</strong>
            <%= @pin.ingredients2 %></p>
      </div>
      </div>    

      <div class="panel panel-default">
      <div class="panel-body">
          <p><strong>Bereidingswijze:</strong>
            <%= @pin.preparation %></p>
      </div>
      </div>    

      <div class="panel panel-default">
      <div class="panel-body">
          <p><strong>Foto van recept:</strong></p>
        	 <%= image_tag @pin.image.url(:medium) %><br> 
      </div>
      </div>

app/views/users/_user.html.erb
<% user = local_assigns.has_key?(:user) ? user : nil %>
<% if user %>
<div class="panel-body">
  <div class="actions">
    <p><b>Chef: </b><%= link_to user.name, user_path(user) %></p></strong>
    <p><%= link_to image_tag(user.image_file_name), user %></p>
    <p>Aantal favoriete recepten: <b><%= user.find_liked_items.size %></b></p>
    <div class="btn-group.pull-right">
      <%= link_to user_path(user), class: "btn btn-info btn-sm" do %>
      <span class="glyphicon glyphicon-fullscreen"></span>
      Bekijk profiel
      <% end %>
      <% if current_user && current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to "Stop volgen", user_unfollow_path(user), :method => :delete, :class => "btn btn-sm btn-danger", :remote => true %>
        <% else %>
          <%= link_to "Chef volgen", user_follow_path(user), :method => :post, :class => "btn btn-sm btn-success", :remote => true %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/users/feeds.html.erb
<h1>Favoriete recepten van jouw vrienden</h1>
<p>Bekijk hier de favoriete recepten die jouw <b><%= current_user.follows.count%></b> vrienden lekker vinden.</p> 
<% if @pins.present? && @pins.to_a.size > 0 %>
<%= render 'pins/show_pin_details' %>  
<% else %>
	<p><u>Voeg eerst vrienden toe om persoonlijke suggesties te ontvangen.</u></p>
<% end %>

<%= link_to users_path, class: "btn btn-success btn-block" do %>
<span class="glyphicon glyphicon-chevron-right"></span>
Voeg vrienden toe<% end %></p>

app/views/users/index.html.erb
<h1>Zoek vrienden</h1>
<p>Bekijk hier de <strong><%= @user.count %> chefs </strong> die lid zijn van Altijd Heerlijk. 
	<u>Tip: Volg jouw favoriete chefs.</u><br>
    <div id="pins" class="transitions-enabled">
      <% @user.each do |user| %>
        <div class="box panel panel-default" id = "user_<%= user.id %>">
            <%= render :partial => 'users/user', :locals => {:user => user} %>
        </div>
        <% end %>
    </div>



app/views/users/my_friends.html.erb
<h1>Mijn vrienden</h1>
<p>Bekijk hier jouw <b><%= current_user.follows.count %></b> vrienden op Altijd Heerlijk. <br>
     <% if @followings.present? && @followings.size > 0 %>
     <div id="pins" class="transitions-enabled">
            <% @followings.each do |user| %>
                <div class="box panel panel-default" id = "user_<%= user.id %>">
                <%= render :partial => 'users/user', :locals => {:user => user} %>
                </div> 
                <% end %>
      <% else %>
          <p><b> Je volgt nog geen andere chefs, bekijk alle chefs op Altijd Heerlijk en volg jouw favoriete chef.</p></b>
      <% end %> 
 </div> 

<%= link_to users_path, class: "btn btn-success btn-block" do %>
<span class="glyphicon glyphicon-chevron-right"></span>
Voeg vrienden toe
<% end %></p>




app/views/users/show.html.erb
<%= link_to :back, class: "btn btn-default" do %>
  <span class="glyphicon glyphicon-chevron-left"></span>
    Back
<% end %>

<br></br> 

<div class="panel panel-default">
  <div class="panel-body">
    <h2><%=@user.name %></h2>
    <p><%= link_to image_tag(@user.image_file_name), @user %></p>
  </div>
</div> 

 <div id="pins" class="transitions-enabled">
              <% @user.find_liked_items.each do |pin| %>
                <div class="box panel panel-default">
                    <div class="panel-body">
                      <div class="actions">
                      <b>Recept:</b>
                          <p><%= link_to pin.description, pin %></p>
                          <p><%= link_to image_tag(pin.image.url), pin %></p>

                      <p><b>Favoriet recept van: </b></p>
                          <% pin.votes_for.voters.each do |p| %> 
                          <% if p.present? %>
                           <p><%= link_to p.name, user_path(@user) %></p>
                           <% end %>   
                      <% end %>

                      </div>   
                    </div>
                </div>
            <% end %>
    </div>